<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CLMC02SH12YG8WM" failures="2" tests="20" name="iOS_Tests.MakePayment_TestSample" time="80.342" errors="0" timestamp="08 Jul 2019 20:11:30 GMT" skipped="1">
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_SpecialSign4" time="0.334">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at iOS_Tests.MakePayment_TestSample.MakePayment_Amount_SpecialSign4(MakePayment_TestSample.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- MakePayment_Amount_SpecialSign4 -->
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_PayWithCards" time="1.652"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_CameraAllow" time="6.240"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_MoreInfoIcon" time="4.564"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_ContinueEnable_Default1" time="0.885"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_ContinueEnable_Default2" time="10.946"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_ContinueDisabled1" time="0.829"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_ErrorM1" time="10.463"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_ErrorM2" time="9.873"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_ContinueDisabled2" time="0.823"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_SpecialSign1" time="12.315">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at iOS_Tests.MakePayment_TestSample.MakePayment_Amount_SpecialSign1(MakePayment_TestSample.java:195)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- MakePayment_Amount_SpecialSign1 -->
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_SpecialSign2" time="0.308"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Amount_SpecialSign3" time="1.881"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Name_Empty" time="4.540"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Name_FillAgain" time="2.730"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Zip_Empty" time="4.857"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Zip_Less5Numbers1" time="2.530"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Zip_Less5Numbers2" time="0.794"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_Cancel" time="3.778"/>
  <testcase classname="iOS_Tests.MakePayment_TestSample" name="MakePayment_CardNumber_Not_A_Test">
    <skipped/>
  </testcase> <!-- MakePayment_CardNumber_Not_A_Test -->
</testsuite> <!-- iOS_Tests.MakePayment_TestSample -->
